#!/usr/bin/env bash
# genpw - minimal password generator
# Copyright (C) 2025  fk29g
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

set -e

PROGRAM="${0##*/}"

print_help() {
    echo "Usage: $PROGRAM [-s] [-n] [length]"
    echo ""
    echo "Flags:"
    echo "  -s  include special characters"
    echo "  -n  include numbers"
    echo "  -h  print help"
}

pw_length=15
tr_chars="a-zA-Z"
num_chars="0-9"
special_chars="\\\\_\-@$%=!?.,;:#\"\'<>(){}[]&|\/^~"

while getopts ":hsn" flag; do
    case "${flag}" in
        h)
            print_help
            exit 0
            ;;
        s)
            tr_chars+="$special_chars"
            ;;
        n)
            tr_chars+="$num_chars"
            ;;
        \?)
            echo "Invalid flag: -$OPTARG"
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

if [[ $# -gt 1 ]]; then
    echo "Too many arguments." >&2
    exit 1
fi

if [[ -n $1 ]]; then
    if [[ $1 =~ ^[0-9]+$ ]]; then
        pw_length="$1"
    else
        echo "Invalid length: $1" >&2
        exit 1
    fi
fi

tr -cd $tr_chars < /dev/urandom | head -c $pw_length
exit 0
